# This is a basic workflow to help you get started with Actions

name: CI

# Controls name: strong-frida build

on:
  push:
    paths:
    - VERSION_

jobs:
  windows_build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2.1.0

    - uses: actions/setup-node@v1.4.2
      with:
        node-version: '12'

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup MSBuild
      id: setup_msbuild
      uses: microsoft/setup-msbuild@v1.0.0

    - name: echo msbuild path
      run: |
        echo "${{ steps.setup_msbuild.outputs.msbuildPath }}"
        msbuild -version

    - name: build frida for Windows
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted
        git clone --recurse-submodules https://github.com/frida/frida
        cd frida
        pwsh .\releng\stage-python.ps1
        New-Item build\tmp-windows -ItemType Directory -ea 0
        python .\releng\generate-version-header.py build\tmp-windows\frida-version.h
        msbuild frida.sln /p:Configuration=Release /p:Platform=x64
when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
